### ISSUE TITLE
hotkey assignment and device selection

### ISSUE THREAD

**Issue by XtremeSounds** [RandScullard/plugin-window-helper#1]
Hi will this script allow us to assign plugin and device selection to a user hotkey press on the keyboard (no mouse)?  Another point its one thing to call up a plugins gui in Bitwig but quite another to actually select the device so that the device pages can be controlled  with a hardware controller.  Does your script solve that issue?

**Comment by RandScullard** [comment]
> Hi will this script allow us to assign plugin and device selection to a user hotkey press on the keyboard (no mouse)?

No, the script is mouse-only. Can you describe for me what you would want the hotkeys to do?

> Another point its one thing to call up a plugins gui in Bitwig but quite another to actually select the device so that the device pages can be controlled with a hardware controller. Does your script solve that issue?

No, you would need a Bitwig controller script to do that. You might want to ask about this on the [Bitwig Discord server](https://discord.com/invite/0g2ZPafIN3eWParf) - someone may have a script that does what you're looking for.

**Comment by XtremeSounds** [comment]
Ok thanks. I think I figured it out.
